### ISSUE TITLE
howto use

### ISSUE THREAD

**Issue by jeee** [andreasbehnke/ansible-role-lms-service#1]
Please specify some info on how to run this.

added host to hosts.yml:
```all:
  children:
     lms: # logitech media server
       hosts:
         192.168.1.217:
           ansible_user: root
           logitech_media_service_version: "8.1.1"
           music_server_http_proxy: False
           music_server_group: "squeezebox"
           music_server_playlist_path: "/squeezelist"
```
           
created site.yml:
```---
- hosts: lms

  pre_tasks:
   - name: update apt cache
     become: yes
     apt: update_cache=yes
     changed_when: False

  roles:
    - ansible-role-lms-service
```
created folder: mkdir roles
check out the role into roles folder

added group check to roles/ansible-role-lms-service/tasks/squeezeboxserver.yml
```  - name: Ensure group "{{ music_server_group }}" exists
    ansible.builtin.group:
      name: "{{ music_server_group }}"
      state: present
```      

run playbook:
ansible-playbook site.yml --limit 192.168.1.217

**Comment by andreasbehnke** [comment]
Hi jeee,

thank you for the usage documentation, I added it to the README file.

Your change to roles/ansible-role-lms-service/tasks/squeezeboxserver.yml is not neccessary. 
The variable music_server_group does not denote an ansible group but a unix user group.
You do not have to take care of it, because now it defaults to "squeezeboxserver".
